# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    imagesDirectory: '%kernel.project_dir%/public/uploads/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    LaSalle\Performance\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    LaSalle\Performance\Photo\Infrastructure\Framework\:
        resource: '../src/Photo/Infrastructure/Framework'
        tags: ['controller.service_arguments']

    Predis\Client:
        arguments:
            - '%env(REDIS_CONNECTION)%'

    LaSalle\Performance\Photo\Application\Event\ApplySepiaFilterOnPhotoCreated:
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, handles: LaSalle\Performance\Photo\Domain\Event\PhotoCreatedDomainEvent }

    LaSalle\Performance\Photo\Application\Event\ApplyDesaturateFilterOnPhotoCreated:
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, handles: LaSalle\Performance\Photo\Domain\Event\PhotoCreatedDomainEvent }

    #          arguments:
    #              - 'redis'
    #              - 6379

    #Doctrine\Common\Cache\RedisCache:
    #   calls:
    #       - method: setRedis
    #         arguments:
    #          - '@Snc\RedisBundle\Client\Phpredis\Client'

    #    calls:
    #        - method: connect
    #          arguments:
    #            - 'redis:6379'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
