doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
        types:
            uuid: LaSalle\Performance\Photo\Infrastructure\Persistence\Doctrine\Type\UuidType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Photo:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Photo/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: LaSalle\Performance\Photo\Domain
