# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
      photo:
        types:
          photo:
            properties:
              id: { fielddata: true }
              nameURL:
              tags: { boost: 8, analyzer: my_analyzer, fielddata: true }
              description: { boost: 8, analyzer: my_analyzer, fielddata: true }
              filter: { boost: 8, analyzer: my_analyzer, fielddata: true }
            persistence:
              driver: orm
              model: LaSalle\Performance\Photo\Domain\Aggregate\Photo
              listener: ~
              provider: ~
              finder: ~
        settings:
          index:
            analysis:
              analyzer:
                my_analyzer:
                  type: keyword
                  tokenizer: lowercase
                  filter: [my_ngram]
              filter:
                my_ngram:
                  type: "nGram"
                  min_gram: 3
                  max_gram: 8

