# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
      photo:
        types:
          photo:
            properties:
              id:
                type: text
              nameURL:
                type: text
              tags:
                type: text
            persistence:
              driver: orm
              model: LaSalle\Performance\Photo\Domain\Aggregate\Photo
              provider: ~
              finder: ~
        settings:
          index:
            analysis:
              filter:
                my_ngram:
                  type: "nGram"
                  min_gram: 1
                  max_gram: 2
