framework:
  messenger:
    transports:
      sepia:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          exchange:
            name: sepia_processor
            type: fanout
          queues:
            sepia: ~
      desaturate:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          exchange:
            name: desaturate_processor
            type: fanout
          queues:
            desaturate: ~
    routing:
      'LaSalle\Performance\Photo\Domain\Event\PhotoCreatedDomainEvent': [sepia, desaturate]
