framework:
  messenger:
    transports:
      image_proccessor:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          exchange:
            name: image_proccessor
            type: fanout
          queues: [sepia, desaturate]
    routing:
      'LaSalle\Performance\Photo\Domain\Event\PhotoCreatedDomainEvent': image_proccessor
